inherit_from: configs/mono/tum/base_config.yaml
Dataset:
  dataset_path: datasets/tum/Studyroom
  Calibration:
    fx: 531.5749
    fy: 531.5749
    cx: 317.99336666666665
    cy: 238.94266666666664
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 640
    height: 480
    distorted: false
    depth_scale: 1000.0
